//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cockroaches.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public int RecordId { get; set; }
        public string RecordType { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int Order { get; set; }
        public System.DateTime AttempOn { get; set; }
        public int StatusId { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime EditedOn { get; set; }
        public string EditedBy { get; set; }
    }
}
