//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cockroaches.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemAttachment
    {
        public int Id { get; set; }
        public int RecordId { get; set; }
        public int EntityType { get; set; }
        public string AttachmentName { get; set; }
        public string AttachmentUrl { get; set; }
        public string AttachmentExtension { get; set; }
        public string ExternalUrl { get; set; }
        public string AttachmentType { get; set; }
        public int Order { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime EditedOn { get; set; }
        public string EditedBy { get; set; }
    }
}
