//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cockroaches.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string DetailDescription { get; set; }
        public string DynamicProperties { get; set; }
        public double Price { get; set; }
        public Nullable<double> CostPrice { get; set; }
        public Nullable<int> ManufactureId { get; set; }
        public string Manufacture { get; set; }
        public int Quantity { get; set; }
        public int QuantityConfirm { get; set; }
        public bool Free { get; set; }
        public Nullable<double> SaleOff { get; set; }
        public bool TopProduct { get; set; }
        public bool BestSeller { get; set; }
        public int CountView { get; set; }
        public string MetaTitle { get; set; }
        public string MetaTags { get; set; }
        public string MetaDescription { get; set; }
        public int StatusId { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime EditedOn { get; set; }
        public string EditedBy { get; set; }
    }
}
